# yaml-language-server: $schema=https://json.schemastore.org/lefthook.json
assert_lefthook_installed: true
commit-msg:
  commands:
    commitlint:
      run: commitlint lint --message "{1}"
    trailers:
      run: git intepret-trailers --in-place --trailer "sign" --trim-empty "{1}"
pre-commit:
  commands:
    go-fmt:
      run: go fmt ./...
    go-test:
      run: go test ./...
    go-vet:
      run: go vet ./...
    go-lint:
      run: golint ./...
    go-sec:
      run: gosec ./...
    go-mod-tidy:
      run: go mod tidy
    gofumpt:
      run: gofumpt -w .
    checkmake:
      run: checkmake Makefile
    editorconfig-checker:
      run: editorconfig-checker
    golangci-lint:
      run: golangci-lint run
    protolint:
      run: protolint lint