version: '3'

tasks:
  generate:
    desc: "Generate Go and gRPC code from proto files."
    cmds:
      - "find ./proto -name '*.proto' -exec protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative {} \\;"
    sources:
      - proto/**/*.proto
    generates:
      - infrastructure/greeter/greeter.pb.go
      - infrastructure/greeter/greeter_grpc.pb.go
      - infrastructure/stack/stack.pb.go
      - infrastructure/stack/stack_grpc.pb.go
    method: checksum
