driver1:
  instanceUrl: localhost
  protocol: https
  port: 8443
  proxyRequired: false
  authenticationType:
    MTLS:
      certFile: ".private/server.crt"
      keyFile: ".private/server.key"

driver2:
  instanceUrl: localhost
  protocol: https
  port: 10443
  proxyRequired: true
  authenticationType:
    MTLS:
      certFile: ".private/server.crt"
      keyFile: ".private/server.key"
    OAuth2:
         clientID: myID
         clientSecret: mySecret
         RefreshToken: MeRefreshToken